spring:
  config:
    import: classpath:rsa-keys/application-rsa-keys.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market-visitia
    username: market-visitia
    password: market-visitia
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      springframework:
        security: debug