include:
  - database.yml

services:
  template-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile-backend
    container_name: dispensa_backend
    image: dispensa/backend:latest
    restart: unless-stopped
    environment:
        DATABASE_URL: jdbc:postgresql://dispensa_database:${DATABASE_PORT}/${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
volumes:
  db-data: {}
