include:
  - database.yml

services:
  template-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile-backend
    container_name: template-backend
    image: template/backend:latest
    restart: unless-stopped
    environment:
        DATABASE_URL: jdbc:postgresql://template-database:5432/${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      template-database:
        condition: service_healthy
volumes:
  template-data: {}
